apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-server:9090
    jsonData:
      httpMethod: GET
      tlsSkipVerify: true

  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-frontend:8080/api_jsonrpc.php
    jsonData:
      authType: "userLogin"
      cacheTTL: ""
      disableDataAlignment: false
      trends: true
      trendsFrom: ""
      trendsRange: ""
      username: "Admin"
    secureJsonData:
      password: zabbix
    basicAuth: false

  - name: MySQL
    type: mysql
    access: proxy
    url: zabbix-mysql:3306
    user: zbx_monitor
    database: zbxlabdb
    secureJsonData:
      password: zbx4monitor
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false